#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : fonts-clear
Version  : 1
Release  : 3
URL      : https://github.com/insilications/fonts-clr/archive/master.zip
Source0  : https://github.com/insilications/fonts-clr/archive/master.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fonts-clear-data = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the fonts-clear package.
Group: Data

%description data
data components for the fonts-clear package.


%prep
%setup -q -n fonts-clr-master
cd %{_builddir}/fonts-clr-master

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611150662
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FCFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export CFFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export LDFLAGS="-O3 -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native "
export CXXFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -fvisibility-inlines-hidden -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1611150662
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
"/usr/share/fonts/Consolas Bold Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Consolas Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Consolas Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Consolas Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Mono.otf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete.otf"
"/usr/share/fonts/Fura Code Bold Nerd Font Complete.ttf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Mono.otf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete.otf"
"/usr/share/fonts/Fura Code Light Nerd Font Complete.ttf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Mono.otf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete.otf"
"/usr/share/fonts/Fura Code Medium Nerd Font Complete.ttf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Mono.otf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete.otf"
"/usr/share/fonts/Fura Code Regular Nerd Font Complete.ttf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Mono.otf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete.otf"
"/usr/share/fonts/Fura Code Retina Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono.otf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete.otf"
"/usr/share/fonts/Inconsolata Bold Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata LGC Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata LGC Nerd Font Complete Windows Compatible (2).ttf"
"/usr/share/fonts/Inconsolata LGC Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf"
"/usr/share/fonts/Inconsolata Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Nerd Font Complete Mono.otf"
"/usr/share/fonts/Inconsolata Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Nerd Font Complete.otf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono.otf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Windows Compatible.otf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete.otf"
"/usr/share/fonts/Inconsolata Regular Nerd Font Complete.ttf"
"/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/InconsolataGo Bold Nerd Font Complete.ttf"
"/usr/share/fonts/InconsolataGo Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/InconsolataGo Nerd Font Complete Mono.ttf"
"/usr/share/fonts/InconsolataGo Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/InconsolataGo Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Black Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Black Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Black Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Black Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Black Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Black Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Black Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Black Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Bold Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro ExtraLight Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Light Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Light Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Light Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Light Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Light Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Light Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Light Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Light Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Medium Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Italic Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Italic Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Italic Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Italic Nerd Font Complete.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Nerd Font Complete Mono Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Nerd Font Complete Mono.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Nerd Font Complete Windows Compatible.ttf"
"/usr/share/fonts/Sauce Code Pro Semibold Nerd Font Complete.ttf"
